# Generated by Django 5.1.3 on 2024-11-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('qoldiq', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='drink/')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='food/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('soni', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_product', models.FloatField(default=0)),
                ('quantity_d', models.FloatField(default=0)),
                ('drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.drinks')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.products')),
            ],
        ),
    ]
