# Generated by Django 5.1.3 on 2024-11-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='drinks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.drinks'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity_d',
            field=models.FloatField(null=True),
        ),
    ]
